---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: argocd/apps/metrics-server
    repoURL: git@github.com:NIXKnight/ArgoCD-Demo.git
    targetRevision: master
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
