---
argo-cd:
  installCRDs: true
  dex:
    enabled: false
  server:
    config:
      repositories: |
        - type: git
          url: git@github.com:NIXKnight/ArgoCD-Demo.git
          sshPrivateKeySecret:
            name: ssh-keys
            key: id_rsa
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argoproj
