---
argo-cd:
  installCRDs: true
  dex:
    enabled: false
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$dE0AHjZA8cAte0CBzwRD6u7sdf0.S3WBsO29iu11dotKdeR53gOSu"
  server:
    config:
      repositories: |
        - type: git
          url: git@github.com:NIXKnight/ArgoCD-Demo.git
          sshPrivateKeySecret:
            name: ssh-keys
            key: id_rsa
      configManagementPlugins: |
        - name: kustomized-helm
          init:
            command: ["/bin/sh", "-c"]
            args: ["helm dependency build || true"]
          generate:
            command: ["/bin/sh", "-c"]
            args: [ "helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE $HELM_VALUES --include-crds > manifest.yaml && kustomize build" ]
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        # kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - argocd.local.nixknight.pk
      https: true
      tls:
        - secretName: argocd-tls-certificate
          hosts:
            - argocd.local.nixknight.pk
