---
argo-cd:
  crds:
    install: true
    keep: false
  dex:
    enabled: false
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$dE0AHjZA8cAte0CBzwRD6u7sdf0.S3WBsO29iu11dotKdeR53gOSu"
    repositories:
      argo-cd-git-repo:
        type: git
        url: git@github.com:NIXKnight/ArgoCD-Demo.git
  repoServer:
    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: "120"
    volumes:
     - name: cmp-plugins
       configMap:
         name: cmp-plugins
    extraContainers:
      - name: cmp-kustomized-helm
        command:
          - "/var/run/argocd/argocd-cmp-server"
        image: nixknight/kube-utils:v0.31
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: kustomized-helm.yaml
            name: cmp-plugins
      - name: cmp-argocd-vault-plugin-helm
        command:
          - "/var/run/argocd/argocd-cmp-server"
        image: nixknight/kube-utils:v0.31
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: argocd-vault-plugin-helm.yaml
            name: cmp-plugins
      - name: cmp-argocd-vault-plugin-kustomize
        command:
          - "/var/run/argocd/argocd-cmp-server"
        image: nixknight/kube-utils:v0.31
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: argocd-vault-plugin-kustomize.yaml
            name: cmp-plugins
  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - argocd.local.nixknight.pk
      https: true
      tls:
        - secretName: argocd-tls-certificate
          hosts:
            - argocd.local.nixknight.pk
