---
argo-cd:
  installCRDs: true
  dex:
    enabled: false
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$dE0AHjZA8cAte0CBzwRD6u7sdf0.S3WBsO29iu11dotKdeR53gOSu"
    repositories: |
      - type: git
        url: git@github.com:NIXKnight/ArgoCD-Demo.git
        sshPrivateKeySecret:
          name: ssh-keys
          key: id_rsa
    configManagementPlugins: |
      - name: kustomized-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build || true"]
        generate:
          command: ["/bin/sh", "-c"]
          args: [ "cd $ARGOCD_ENV_ENVIRONMENT_DIR && helm template ../../ --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE -f values.yaml --include-crds > manifest.yaml && kustomize build" ]
      - name: argocd-vault-plugin-kustomize
        generate:
          command: ["sh", "-c"]
          args: ["kustomize build . | argocd-vault-plugin generate -"]
      - name: argocd-vault-plugin-helm
        init:
          command: ["/bin/sh", "-c"]
          args: ["helm dependency build || true"]
        generate:
          command: ["/bin/sh", "-c"]
          args: [ "helm template . --name-template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE -f $ARGOCD_ENV_ENVIRONMENT_DIR/values.yaml --include-crds | argocd-vault-plugin generate -" ]
  repoServer:
    initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]
        env:
          - name: AVP_VERSION
            value: "1.12.0"
        args:
          - |
            wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64
            chmod +x argocd-vault-plugin
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - name: custom-tools
            mountPath: /custom-tools
    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: "120"
    volumeMounts:
      - name: custom-tools
        mountPath: /usr/local/bin/argocd-vault-plugin
        subPath: argocd-vault-plugin
    volumes:
      - name: custom-tools
        emptyDir: {}
  server:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-issuer
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - argocd.local.nixknight.pk
      https: true
      tls:
        - secretName: argocd-tls-certificate
          hosts:
            - argocd.local.nixknight.pk
