---
cilium:
  kubeProxyReplacement: partial
  image:
    pullPolicy: IfNotPresent
    useDigest: false
  operator:
    image:
      pullPolicy: IfNotPresent
      useDigest: false
  nodeinit:
    enabled: true
  hostServices:
    enabled: false
  externalIPs:
    enabled: true
  bpf:
    masquerade: false
  ipam:
    mode: kubernetes
  nodePort:
    enabled: true
  hostPort:
    enabled: true
