---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/app
  - ../../../apps/argo-cd/app
  - ../../../apps/metrics-server/app
  - ../../../apps/tekton-pipeline/app
  - ../../../apps/tekton-dashboard/app
resources:
  - root.yaml
