---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argoproj
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: argocd/apps/argocd
    repoURL: git@github.com:NIXKnight/ArgoCD-Demo.git
    targetRevision: master
  destination:
    namespace: argoproj
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
