---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
spec:
  project: default
  source:
    path: argocd/manifests
    repoURL: git@github.com:NIXKnight/ArgoCD-Demo.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
